name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Clean static directory (optional)
        run: rm -rf static/sticker-editor || true  # 清理旧构建产物

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install React App Dependencies
        run: |
          cd themes/kgmnrin/assets/sticker-editor
          npm ci --prefer-offline  # 使用ci安装依赖更可靠

      - name: Build React App
        run: |
          npm run build-sticker-editor

      - name: Copy React Build to Hugo Static
        run: |
          mkdir -p static/sticker-editor
          cp -r themes/kgmnrin/static/sticker-editor/* static/sticker-editor/

      - name: Setup Hugo Extended
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Build Hugo
        run: hugo --minify

      - name: Copy React Build to Hugo Public
        run: |
          mkdir -p static/sticker-editor
          cp -r themes/kgmnrin/static/sticker-editor/* public/sticker-editor/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master
          force_orphan: true