name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches: [ dev ]  # 当 dev 分支有推送时触发

jobs:
  deploy:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的 Ubuntu 环境

    steps:
      # 1. 检出代码（包括子模块，如果你的主题是 Git 子模块）
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # 2. 安装 Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"  # 使用最新版 Hugo

      # 3. 构建 Hugo 站点（生成 public/ 目录）
      - name: Build
        run: hugo --minify  # --minify 用于压缩 HTML/CSS/JS

      # 4. 部署到 GitHub Pages（推送到 master 分支）
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub 自动提供的 token
          publish_dir: ./public  # 要部署的目录
          publish_branch: master  # 推送到 master 分支（GitHub Pages 默认分支）
